### ISSUE TITLE
Feature request: See moves/Pokemon after selecting an action

### ISSUE THREAD

**Issue by HarrisonMc555** [smogon/pokemon-showdown-client#1523]
Would we be interested in adding the ability to still see the moves/Pokemon after selecting an action?

Currently, after you select an action (move or switch), your moves and Pokemon disappear until the opponent chooses an action. Only then do the moves and Pokemon re-appear.

This is especially frustrating in random battles when you want to look at the other Pokemon you have (and their moves), but don't want every turn to take 2 minutes. If you could choose a move and then take a closer look at the other Pokemon that would be great.

Some may think there's some ambiguity as to whether or not you should show the current Pokemon's moves or the moves of the Pokemon you're switching into. However, I would strongly argue in favor of continuing to show the moves of the current Pokemon. This would simplify things and would mean that the move/Pokemon select panel doesn't change after selecting an action. We could simply display the current action text (e.g. "Pikachu will use Thunderbolt") above/below the moves/Pokemon.

If this is something we'd be willing to look into, I'd be happy to look into implementing it. I don't have a ton of experience in TypeScript but I've done plenty of development in other languages.

**Comment by Zarel** [comment]
This is already done in the Preact client:

https://github.com/smogon/pokemon-showdown-client/blob/54dce68ade88655a8c57509a4bd128a88bdabbde/src/panel-battle.tsx#L538

This is related to your Suggestion thread on Smogon:

https://www.smogon.com/forums/threads/show-moves-pokemon-after-selecting-action.3664994/

I'm not going to keep this issue open mostly because it _is_ fixed on the Preact client. I will, of course, accept a PR to backport it to the old client, but I don't think it's important enough to keep an open issue for.
